# Neural Turing Machine

All the logical Representations done in the paper (arXiv:1410.5401 [cs.NE]) understood during the first read through the paper

## Reading 

In [1]:
import numpy as np

Memory matrix $M_t$ is of size NxM where N is the number of memory locations and M is the vector size at each location.

For the weights emitted by the $\verb|Read Head|$ for attention purposes, let it be defined by the vector $w_t$, which defines the weight over the N locations emitted by the $\verb|Read Head|$ at time $t$.

Note that these weights are normalised, thus, $w_t$ is should obey the following constraints.

$\sum_i w_t(i) = 1$ and $0 \le w_t(i) \le 1$,  $\forall i$

The output will be a size $M$ long vector $r_t$ which is a combination of the weights $w_t(i)$ and the row-vectors $M_t(i)$, as following:-

$r_t = \sum_i w_t(i) M_t(i)$

this is just the dot product of $w_t$ with $M_t$

In [2]:
N = 10
M = 5

#### Initializing random Memory

In [49]:
memory_t = np.random.randn(N,M)

In [50]:
memory_t

array([[ 1.02566554,  0.26984035,  2.32146663, -0.04645675, -0.74322073],
       [-0.4219099 , -0.69259713,  1.26132611,  0.03370328,  1.00963184],
       [ 0.49032976, -1.21833442,  0.99009593, -1.74248038,  1.10700821],
       [-1.14657412, -0.38178142, -1.70991989, -0.37022442,  0.63975417],
       [-0.16097788, -0.41253773, -2.31352148, -1.72432896,  1.87729238],
       [ 0.50284768,  1.25865532,  1.44719464, -3.23064775, -0.38729273],
       [ 0.44668247,  1.02202843,  0.40753485, -0.54830743, -3.25076998],
       [-0.85941436, -0.20088155, -0.42805193, -0.04100567, -1.39025753],
       [-0.32842488,  0.75626153, -1.09374307, -1.45523358, -1.99149845],
       [ 0.48134513, -0.05964692, -0.22696669,  0.82176327,  0.9962702 ]])

#### Read Weight for this time step being Initialised Below

In [51]:
w_t = np.random.rand(1,N)

In [52]:
w_t = w_t/np.sum(w_t)

In [53]:
w_t

array([[0.12663217, 0.01609757, 0.13725025, 0.13981906, 0.00046411,
        0.12766177, 0.16276443, 0.04685124, 0.15513073, 0.08732867]])

$w_t$ is constraied accordingly now

In [54]:
np.sum(w_t)

1.0000000000000002

In [55]:
r_t = np.dot(w_t, memory_t)

Shape check for output $r_t$

In [56]:
r_t.shape == (1,M)

True

## Writing 

There are 3 objects in this module

1. Weight vector $w_t$ emitted by $\verb|Write Head|$ at time $t$
2. Erase vector $e_t$ of length M, whose elements lie in the interval $(0,1)$
3. Add vector $a_t$ of length M

In the writing module, each write is decomposed in two steps *Erase & Add*

*Erase Step*

 $\hat M_t(i) = M_{t-1}(i)[\mathbf{1} - w_t(i)e_t]$
 
 Here Mulitplication is Pointwise
 
*Add Step*
    
 $M_t(i) = \hat M_t(i) + w_t(i)a_t$

In [68]:
write_w_t = np.random.rand(N,1)
e_t = np.random.rand(1,M)
a_t = np.random.randn(1,M)

### ERASE

In [ ]:
M_hat_t = memory_t

In [84]:
write_w_t,e_t

(array([[0.67363339],
        [0.84866616],
        [0.0744187 ],
        [0.86792403],
        [0.00443963],
        [0.93665241],
        [0.87952246],
        [0.52303087],
        [0.17449281],
        [0.18220917]]),
 array([[0.54679476, 0.17789317, 0.83328383, 0.95704984, 0.91626833]]))

In [93]:
matrix = np.dot(write_w_t,e_t) #Each row of matrix will provide the corresponding row (ith)in the Erase Equation  

In [95]:
matrix

array([[3.68339207e-01, 1.19834781e-01, 5.61327809e-01, 6.44700724e-01,
        6.17228937e-01],
       [4.64046210e-01, 1.50971917e-01, 7.07179789e-01, 8.12215810e-01,
        7.77605923e-01],
       [4.06917551e-02, 1.32385787e-02, 6.20118991e-02, 7.12224044e-02,
        6.81874975e-02],
       [4.74576313e-01, 1.54397761e-01, 7.23227063e-01, 8.30646554e-01,
        7.95251302e-01],
       [2.42756589e-03, 7.89779696e-04, 3.69947108e-03, 4.24894623e-03,
        4.06789146e-03],
       [5.12156632e-01, 1.66624070e-01, 7.80497311e-01, 8.96423040e-01,
        8.58224941e-01],
       [4.80918272e-01, 1.56461041e-01, 7.32891844e-01, 8.41746826e-01,
        8.05878573e-01],
       [2.85990543e-01, 9.30436225e-02, 4.35833172e-01, 5.00566615e-01,
        4.79236627e-01],
       [9.54117533e-02, 3.10410794e-02, 1.45402036e-01, 1.66998314e-01,
        1.59882234e-01],
       [9.96310176e-02, 3.24137669e-02, 1.51831952e-01, 1.74383253e-01,
        1.66952488e-01]])

In [97]:
matrix = 1 - matrix
matrix

array([[0.63166079, 0.88016522, 0.43867219, 0.35529928, 0.38277106],
       [0.53595379, 0.84902808, 0.29282021, 0.18778419, 0.22239408],
       [0.95930824, 0.98676142, 0.9379881 , 0.9287776 , 0.9318125 ],
       [0.52542369, 0.84560224, 0.27677294, 0.16935345, 0.2047487 ],
       [0.99757243, 0.99921022, 0.99630053, 0.99575105, 0.99593211],
       [0.48784337, 0.83337593, 0.21950269, 0.10357696, 0.14177506],
       [0.51908173, 0.84353896, 0.26710816, 0.15825317, 0.19412143],
       [0.71400946, 0.90695638, 0.56416683, 0.49943338, 0.52076337],
       [0.90458825, 0.96895892, 0.85459796, 0.83300169, 0.84011777],
       [0.90036898, 0.96758623, 0.84816805, 0.82561675, 0.83304751]])

In [98]:
matrix.shape

(10, 5)

In [103]:
M_hat_t = np.multiply(memory_t,matrix)

In [104]:
M_hat_t.shape == (N,M)

True

### ADD

In [105]:
matrix2 = np.dot(write_w_t,a_t)

In [106]:
matrix2.shape

(10, 5)

In [107]:
M_hat_t.shape

(10, 5)

In [112]:
M_t = (M_hat_t + matrix2)

### Final Output

In [115]:
M_t.shape == (N,M)

True

## Addressing Mechanism 

### 1. Focusing by Content

Parameters:-

1. $k_t$: Vector(M), Key Vector.
2. $\beta_t$: Scalar, Key Strength at time t.
3. $K[.,.]$: Function, Similarity Measure.

Equation:-

$\Large w_t^c(i) = \frac{exp( \beta_tK[\mathbf{k}_t, \mathbf{M}_t(i)] )}{\sum_j exp(\beta_tK[\mathbf{k}_t, \mathbf{M}_t(j)])} $

For the similarity measure, the paper used cosine similarity

In [152]:
def Cosine_similarity(u,v):
    u,v = u.reshape(1,-1),v.reshape(-1,1)
    return np.dot(u,v)/(np.linalg.norm(u)*np.linalg.norm(v))

Initializing Random Key vector and $\beta_t$

In [153]:
k_t = np.random.randn(1,M)
b_t = 1
K = Cosine_similarity

In [154]:
K_on_each_row = np.apply_along_axis(K, 1, M_t,k_t).reshape(-1,1)

In [155]:
K_on_each_row

array([[-0.62821605],
       [ 0.22539885],
       [ 0.3690185 ],
       [ 0.13202885],
       [ 0.51681715],
       [-0.24193407],
       [-0.54663512],
       [-0.36324891],
       [-0.56025637],
       [ 0.44502288]])

In [156]:
w_ct = np.exp(b_t * K_on_each_row) / np.sum(b_t * np.exp(K_on_each_row))

In [157]:
w_ct

array([[0.05209612],
       [0.12232792],
       [0.14122085],
       [0.11142317],
       [0.16371443],
       [0.07665941],
       [0.05652434],
       [0.06790146],
       [0.05575963],
       [0.15237268]])

In [159]:
w_ct.shape == (N,1)

True

### 2. Focusing by Location

$\Large \mathbf{w}_t^g = g_t\mathbf{w}_t^c + (1 - g_t)\mathbf{w}_{t-1}$

Where $g_t$ is the scalar Interpolation Gate $\in$ (0,1) and $w_{t-1}$ is the weght vector produced by the *head* in the previous time step

In [161]:
g_t = 1
w_prev = np.random.rand(N,1)

The above variables initialised just for reference, as this notebook doesn't aims to implement TNM

In [162]:
w_gt = g_t * w_ct + (1 - g_t) * w_prev

In [164]:
w_gt

array([[0.05209612],
       [0.12232792],
       [0.14122085],
       [0.11142317],
       [0.16371443],
       [0.07665941],
       [0.05652434],
       [0.06790146],
       [0.05575963],
       [0.15237268]])

After Interpolation, each head emits a *shift weighting* $\mathbf{s}_t$

NOTE: **Defining Shift Locations/Range as just a random vector (for now)**

In [165]:
s_t = np.random.rand(1,N)

In [167]:
s_t = s_t/np.sum(s_t)

In [170]:
s_t

array([[0.06053958, 0.10537119, 0.12345044, 0.04555618, 0.10079448,
        0.13570933, 0.07399194, 0.13712262, 0.12233864, 0.09512561]])

In [187]:
w_gt

array([[0.05209612],
       [0.12232792],
       [0.14122085],
       [0.11142317],
       [0.16371443],
       [0.07665941],
       [0.05652434],
       [0.06790146],
       [0.05575963],
       [0.15237268]])

In [218]:
w_hat_t = np.convolve(w_gt.reshape(-1), s_t.reshape(-1))[:N]

In [219]:
w_hat_t

array([0.00315388, 0.01289511, 0.02787058, 0.03910086, 0.04990956,
       0.06148034, 0.0714763 , 0.07357927, 0.08621996, 0.10353205])

Defining Sharpening Factor $\gamma_t \ge 1$

In [220]:
gamma_t = 1.5

In [221]:
w_new_t = np.power(w_hat_t,gamma_t)/np.sum(np.power(w_hat_t,gamma_t))

In [222]:
w_new_t

array([0.00128238, 0.01060198, 0.03368747, 0.05597947, 0.08072816,
       0.1103707 , 0.13835424, 0.1445049 , 0.18329942, 0.24119128])

In [226]:
w_new_t.shape == (N,)

True